### PR TITLE
feat: change physics service URL

### PR DESCRIPTION
**Pull request by maelle**
@salvafern I am getting the same error as before.

``` r
service <- EMODnetWFS::emodnet_init_wfs_client("physics")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> Loading IANA mime types...
#> No encoding supplied: defaulting to UTF-8.
#> ✔ WFS client created successfully
#> ℹ Service: 'https://prod-geoserver.emodnet-physics.eu/geoserver/ows'
#> ℹ Version: '2.0.0'
service
#> <WFSClient>
#>   Inherits from: <OWSClient>
#>   Public:
#>     attrs: list
#>     capabilities: WFSCapabilities, OWSCapabilities, OGCAbstractObject, R6
#>     clone: function (deep = FALSE) 
#>     defaults: list
#>     describeFeatureType: function (typeName) 
#>     element: AbstractObject
#>     encode: function (addNS = TRUE, geometa_validate = TRUE, geometa_inspire = FALSE, 
#>     ERROR: function (text) 
#>     getCapabilities: function () 
#>     getCASUrl: function () 
#>     getClass: function () 
#>     getClassName: function () 
#>     getConfig: function () 
#>     getFeatures: function (typeName, ...) 
#>     getFeatureTypes: function (pretty = FALSE) 
#>     getHeaders: function () 
#>     getNamespaceDefinition: function (recursive = FALSE) 
#>     getPwd: function () 
#>     getToken: function () 
#>     getUrl: function () 
#>     getUser: function () 
#>     getVersion: function () 
#>     INFO: function (text) 
#>     initialize: function (url, serviceVersion = NULL, user = NULL, pwd = NULL, 
#>     isFieldInheritedFrom: function (field) 
#>     logger: function (type, text) 
#>     loggerType: NULL
#>     namespace: OWSNamespace, R6
#>     reloadCapabilities: function () 
#>     url: https://prod-geoserver.emodnet-physics.eu/geoserver/ows
#>     verbose.debug: FALSE
#>     verbose.info: FALSE
#>     version: 2.0.0
#>     WARN: function (text) 
#>     wrap: FALSE
#>   Private:
#>     cas_url: NULL
#>     config: request
#>     fromComplexTypes: function (value) 
#>     headers: EMODnetWFS R package https://github.com/EMODnet/EMODnetWFS
#>     pwd: NULL
#>     serviceName: WFS
#>     system_fields: verbose.info verbose.debug loggerType wrap element names ...
#>     token: NULL
#>     user: NULL
#>     xmlElement: AbstractObject
#>     xmlExtraNamespaces: NULL
#>     xmlNamespacePrefix: OWS
#>     xmlNodeToCharacter: function (x, ..., indent = "", tagSeparator = "\n")
EMODnetWFS::emodnet_get_wfs_info(service)
#> Space required after the Public Identifier
#> SystemLiteral " or ' expected
#> SYSTEM or PUBLIC, the URI is missing
#> Opening and ending tag mismatch: hr line 0 and body
#> Opening and ending tag mismatch: body line 0 and html
#> EndTag: '</' not found
#> Error in `purrr::map_chr()`:
#> ℹ In index: 4.
#> Caused by error:
#> ! 1: Space required after the Public Identifier
#> 2: SystemLiteral " or ' expected
#> 3: SYSTEM or PUBLIC, the URI is missing
#> 4: Opening and ending tag mismatch: hr line 0 and body
#> 5: Opening and ending tag mismatch: body line 0 and html
#> 6: EndTag: '</' not found

#> Backtrace:
#>      ▆
#>   1. ├─EMODnetWFS (local) `<fn>`(wfs = service)
#>   2. │ ├─... %>% ... at EMODnetWFS/R/info.R:50:2
#>   3. │ └─tibble::tibble(...)
#>   4. │   └─tibble:::tibble_quos(xs, .rows, .name_repair)
#>   5. │     └─rlang::eval_tidy(xs[[j]], mask)
#>   6. ├─tidyr::separate(...)
#>   7. ├─purrr::map_chr(capabilities$getFeatureTypes(), guess_layer_format)
#>   8. │ └─purrr:::map_("character", .x, .f, ..., .progress = .progress)
#>   9. │   ├─purrr:::with_indexed_errors(...)
#>  10. │   │ └─base::withCallingHandlers(...)
#>  11. │   ├─purrr:::call_with_cleanup(...)
#>  12. │   └─EMODnetWFS (local) .f(.x[[i]], ...)
#>  13. │     └─layer$getDescription(pretty = TRUE) at EMODnetWFS/R/info.R:103:2
#>  14. │       └─WFSDescribeFeatureType$new(...)
#>  15. │         └─ows4R (local) initialize(...)
#>  16. │           └─self$execute()
#>  17. │             └─private$GET(...)
#>  18. │               └─XML::xmlParse(text)
#>  19. ├─XML (local) `<fn>`(`<chr>`)
#>  20. │ └─base::stop(e)
#>  21. └─purrr (local) `<fn>`(`<XMLPrsEL>`)
#>  22.   └─cli::cli_abort(...)
#>  23.     └─rlang::abort(...)
```

<sup>Created on 2023-02-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by maelle** [comment]
So maybe worth a report after all?

**Comment by salvafern** [comment]
Yes! I have reported it to EMODnet just a moment ago :)

**Comment by maelle** [comment]
@salvafern have you heard anything back?

**Comment by salvafern** [comment]
Yes, the issue should be fixed. I just tried and no errors:

```r
# not a reprex cause this was faster :) 

service <- EMODnetWFS::emodnet_init_wfs_client("physics")
EMODnetWFS::emodnet_get_wfs_info(service)
# A tibble: 108 × 9
# data_source service_name service_url   layer_namespace layer_name title abstract class format
# <chr>       <chr>        <chr>         <chr>           <chr>      <chr> <chr>    <chr> <chr> 
#   1 emodnet_wfs physics      https://geos… emodnet         EMODPACE_… EMOD… ""       WFSF… data.…
#  2 emodnet_wfs physics      https://geos… emodnet         EP_GEO_PS… EMOD… "Global… WFSF… sf    
#  3 emodnet_wfs physics      https://geos… emodnet         EP_GEO_IN… EMOD… "Sea Le… WFSF… sf    
#  4 emodnet_wfs physics      https://geos… emodnet         EP_GEO_SO… EMOD… "Global… WFSF… sf    
#  5 emodnet_wfs physics      https://geos… emodnet         EP_GEO_PS… EMOD… "Global… WFSF… sf    
#  6 emodnet_wfs physics      https://geos… emodnet         EP_GEO_IN… EMOD… "EMODne… WFSF… sf    
#  7 emodnet_wfs physics      https://geos… emodnet         EP_GEO_IN… EMOD… "EMODne… WFSF… sf    
#  8 emodnet_wfs physics      https://geos… emodnet         EP_GEO_IN… EMOD… "EMODne… WFSF… sf    
#  9 emodnet_wfs physics      https://geos… emodnet         EP_GEO_PS… EMOD… "Collec… WFSF… sf    
# 10 emodnet_wfs physics      https://geos… emodnet         EP_GEO_GR… EMOD… "Global… WFSF… sf   

```

**Comment by maelle** [comment]
unrelated failures

**Pull request merged**
