### PR TITLE
refactor: run linters

### LINKED ISSUE #120: run new linters on codebase
https://www.tidyverse.org/blog/2022/07/lintr-3-0-0/#google-linters

### PR DESCRIPTION
**Pull request by maelle**
Fix #120

### CODE REVIEW

**Comment by maelle** [comment]
Only failures related to #121

**Comment by annakrystalli** [comment]
Are ready for a review on this PR?

**Review by annakrystalli — COMMENTED** [review]
Really liking these linters! Will set up for EMODnetWCS also!

**Comment by maelle** [comment]
@annakrystalli yes it's now ready!

Given some linters have false positives, for now it's not set up automatically.

**Comment by annakrystalli** [comment]
Do you just run them manually locally then? If so, should we add a note in the contributing guidelines about it if so so other devs know how to deploy them?

**Review by annakrystalli — APPROVED** [review]
This all looks great to me. I've added my only comment to the PR discussion

**Pull request merged**
