### PR TITLE
add pkgdown docs

### PR DESCRIPTION
**Pull request by annakrystalli**
Adding a documentation website so users can browse documentation (function references and vignettes) online.

Because it's supposed to push to `gh-pages` , not sure whther this will work unless it's merged to `master`. Let's see!

### CODE REVIEW

**Comment by annakrystalli** [comment]
@salvafern , if all the checks pass (which it should as there's nothing affecting package functionality in this PR), do you mind if I merge it in and test out whether the docs will build on `master`?

**Comment by annakrystalli** [comment]
Just for context, rather than having to build docs locally, what this GitHub Action does is automatically build the pkgdown site and push it to a `gh-pages` branch from which it is served. That emasn we don't need to worry about rebuilding dowcs everytime we make changes. They will build automatically when something is pushed or merged into master.

**Comment by salvafern** [comment]
Not at all! I'll merge them when the checks are completed. Where will be the package website hosted?

**Comment by annakrystalli** [comment]
On GitHub through gh-pages. I'll enable it through the Pages panel on Settings. Here's a short demo of how it works: https://annakrystalli.me/rrresearchACCE20/packaging-functionality.html#create-documentation-site

**Comment by annakrystalli** [comment]
BTW, I have admin right to merge it. Just wanted to make sure you are aware and ok with it 😊

**Comment by salvafern** [comment]
Ok perfect! Thanks :)

**Comment by annakrystalli** [comment]
I'm going to ignore the macos devel test failures as it's not really relevant to this PR and will hopeful be resolved by release anyways for the rest of the functionality.

**Comment by annakrystalli** [comment]
Done! You can check out the site here @salvafern ! https://emodnet.github.io/EMODnetWFS/

The link to the docs site is also now on the repo landing page: 
image

**Pull request merged**
