### PR TITLE
Upgrade pkgdown

### PR DESCRIPTION
**Pull request by annakrystalli**
Upgrade to pkgdown 2.0.0 which allows for use of bootstrap 5. (thanks for the tip @maelle!

Also moved and renamed hex to allow automatic placement on the site as well as autogeneration of favicon.

### CODE REVIEW

**Comment by annakrystalli** [comment]
This allows us to customise the site with EMODnet branding (colours, fonts etc) much more easily should we wish to do so.

**Review by salvafern — COMMENTED** [review]
Hi, I don't see any problem with the upgrade but I couldn't test locally, so cannot say much. 

Something is failing in the [emodnetwfs vignette](https://github.com/EMODnet/EMODnetWFS/blob/master/vignettes/emodnetwfs.Rmd). Most likely in the code chunk that creates an html map viewer with `mapview`: (Error : path for html_dependency not found: )

This error is raised also when knitting the vignette, but not when running the code chunk. I'll keep debugging.

```r
library(pkgdown)

pkgdown::build_site()
#> -- Installing package into temporary library -------------------------------------------
#>     == Building pkgdown site =======================================================
#>     Reading from: 'C:/Users/salvadorf/Documents/EMODnet/EMODnet III/EMODnetWFS'
#> Writing to:   'C:/Users/salvadorf/Documents/EMODnet/EMODnet III/EMODnetWFS/docs'
#> -- Initialising site -----------------------------------------------------------
#>     Copying '../../../R/R-4.0.2/library/pkgdown/BS5/assets/link.svg' to 'link.svg'
#> Copying '../../../R/R-4.0.2/library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
#> Copying 'pkgdown/favicon/apple-touch-icon-120x120.png' to 'apple-touch-icon-120x120.png'
#> Copying 'pkgdown/favicon/apple-touch-icon-152x152.png' to 'apple-touch-icon-152x152.png'
#> Copying 'pkgdown/favicon/apple-touch-icon-180x180.png' to 'apple-touch-icon-180x180.png'
#> Copying 'pkgdown/favicon/apple-touch-icon-60x60.png' to 'apple-touch-icon-60x60.png'
#> Copying 'pkgdown/favicon/apple-touch-icon-76x76.png' to 'apple-touch-icon-76x76.png'
#> Copying 'pkgdown/favicon/apple-touch-icon.png' to 'apple-touch-icon.png'
#> Copying 'pkgdown/favicon/favicon-16x16.png' to 'favicon-16x16.png'
#> Copying 'pkgdown/favicon/favicon-32x32.png' to 'favicon-32x32.png'
#> Copying 'pkgdown/favicon/favicon.ico' to 'favicon.ico'
#> Copying 'logo.svg' to 'logo.svg'
#> -- Building home ---------------------------------------------------------------
#>     Writing 'authors.html'
#> Reading 'LICENSE.md'
#> Writing 'LICENSE.html'
#> Writing 'LICENSE-text.html'
#> Writing '404.html'
#> -- Building function reference -------------------------------------------------
#>     Writing 'reference/index.html'
#> Copying 'man/figures/README-unnamed-chunk-5-1.png' to 'reference/figures/README-unnamed-chunk-5-1.png'
#> Reading 'man/emodnet_get_layers.Rd'
#> Writing 'reference/emodnet_get_layers.html'
#> Reading 'man/emodnet_get_wfs_info.Rd'
#> Writing 'reference/emodnet_get_wfs_info.html'
#> Reading 'man/emodnet_init_wfs_client.Rd'
#> Writing 'reference/emodnet_init_wfs_client.html'
#> Reading 'man/emodnet_wfs.Rd'
#> Writing 'reference/emodnet_wfs.html'
#> Reading 'man/layer_attributes_get_names.Rd'
#> Writing 'reference/layer_attributes_get_names.html'
#> Reading 'man/layer_attributes_summarise.Rd'
#> Writing 'reference/layer_attributes_summarise.html'
#> Reading 'man/layer_attributes_tbl.Rd'
#> Writing 'reference/layer_attributes_tbl.html'
#> Reading 'man/layer_attribute_descriptions.Rd'
#> Writing 'reference/layer_attribute_descriptions.html'
#> Reading 'man/layer_attribute_inspect.Rd'
#> Writing 'reference/layer_attribute_inspect.html'
#> Reading 'man/pipe.Rd'
#> Writing 'reference/pipe.html'
#> -- Building articles -----------------------------------------------------------
#>     Writing 'articles/index.html'
#> Reading 'vignettes/emodnetwfs.Rmd'
#> -- RMarkdown error -------------------------------------------------------------
#>     |
#>     Attaching package: 'dplyr'
#> 
#> The following objects are masked from 'package:stats':
#>     
#>     filter, lag
#> 
#> The following objects are masked from 'package:base':
#>     
#>     intersect, setdiff, setequal, union
#> 
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
#> Error : path for html_dependency not found: 
#>     In addition: Warning messages:
#>     1: package 'mapview' was built under R version 4.0.4 
#> 2: package 'dplyr' was built under R version 4.0.4 
#> 3: package 'sf' was built under R version 4.0.3 
#> 4: attribute variables are assumed to be spatially constant throughout all geometries 
#> --------------------------------------------------------------------------------
#>     Error : Failed to render RMarkdown
#> Error: callr subprocess failed: Failed to render RMarkdown
#> Type .Last.error.trace to see where the error occurred

.Last.error.trace
#> 
#> Stack trace:
#>     
#> Process 17968:
#> 1. pkgdown::build_site()
#> 2. pkgdown:::build_site_external(pkg = pkg, examples = examples,  ...
#> 3. callr::r(function(..., crayon_enabled, crayon_colors, pkgdown_internet) { ...
#> 4. callr:::get_result(output = out, options)
#> 5. throw(newerr, parent = remerr[[2]])
#>    
#> x callr subprocess failed: Failed to render RMarkdown 
#>    
#> Process 21288:
#> 17. (function (..., crayon_enabled, crayon_colors, pkgdown_internet)  ...
#> 18. pkgdown::build_site(...)
#> 19. pkgdown:::build_site_local(pkg = pkg, examples = examples, run_dont_run = ...
#> 20. pkgdown:::build_articles(pkg, lazy = lazy, override = override,  ...
#> 21. purrr::walk(pkg$vignettes$name, build_article, pkg = pkg, quiet = quiet,  ...
#> 22. purrr:::map(.x, .f, ...)
#> 23. pkgdown:::.f(.x[[i]], ...)
#> 24. pkgdown:::render_rmarkdown(pkg, input = input, output = output_file,  ...
#> 25. base:::tryCatch(callr::r_safe(function(...) rmarkdown::render(...),  ...
#> 26. base:::tryCatchList(expr, classes, parentenv, handlers)
#> 27. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#> 28. value[[3L]](cond)
#> 29. rlang:::abort("Failed to render RMarkdown", parent = cnd)
#> 30. rlang:::signal_abort(cnd)
#> 31. base:::signalCondition(cnd)
#> 32. (function (e)  ...
#> 
#> x Failed to render RMarkdown 


sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C 
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] statsgraphics  grDevices utilsdatasets  methods   base
#> 
#> other attached packages:
#> [1] reprex_2.0.0  pkgdown_2.0.1
#> 
#> loaded via a namespace (and not attached):
#> [1] rstudioapi_0.13 knitr_1.31 magrittr_2.0.1  R6_2.5.0   rlang_0.4.10   
#> [6] fastmap_1.1.0   fansi_0.4.2tools_4.0.2xfun_0.21  utf8_1.1.4
#> [11] cli_2.5.0  withr_2.4.1htmltools_0.5.2 ellipsis_0.3.1  yaml_2.2.1
#> [16] rprojroot_2.0.2 digest_0.6.27   tibble_3.1.0    lifecycle_1.0.0 crayon_1.4.1   
#> [21] processx_3.5.1  callr_3.7.0purrr_0.3.4ps_1.6.0   vctrs_0.3.6    
#> [26] fs_1.5.0   memoise_2.0.0   glue_1.4.2 cachem_1.0.4    evaluate_0.14  
#> [31] rmarkdown_2.11  compiler_4.0.2  pillar_1.6.0    desc_1.3.0 pkgconfig_2.0.3
```

**Comment by salvafern** [comment]
Ok fixed. Indeed it was `mapview`. I did reinstall `pandoc`, `rmarkdown`, `pkgdown` and `mapview`, now works fine locally. 

I think it looks good 😄 maybe we can try different themes? e.g. make the text columns wider: it is hard to read the output of the sf objects.

**Comment by annakrystalli** [comment]
Great! And sure! Have a look at the customisation vignette, especially the capabilities through `bslib` seem great! https://pkgdown.r-lib.org/articles/customise.html

**Comment by salvafern** [comment]
Yea looks like we can change pretty much everything :) 

Anyways because the migration to the europa.eu domain, the visual identity of the project might change. Maybe we should not put much time on the style right now as we may have to change it in a few months. I'll ask around for more info. 

Can you have a look at the R-CMD-check? https://github.com/EMODnet/EMODnetWFS/actions/runs/1578237495

**Comment by annakrystalli** [comment]
Sure. I'm actually on annual leave today and tomorrow (just arrived back home! 😃🇬🇷) so I'll take a look at it on Fri when I'm back at work.

**Pull request merged**
