### PR TITLE
Move service tests to separate github action

### PR DESCRIPTION
**Pull request by salvafern**
A partial fix of #24

- Deleted [test-services.R](https://github.com/EMODnet/EMODnetWFS/commit/d03316fe13acba45bbde656a5384a2235ed67069#diff-20f005c0f16c5448cd2601922ba839da23a8f7dde28d61f8bcb83baa96a8d6cd)
- Created pipeline [Test-Services.yaml](https://github.com/EMODnet/EMODnetWFS/blob/3bf49f9b43cacff992da3b1910ad48db8715745c/.github/workflows/Test-Services.yaml)

I tested this workflow and seems to work fine: e.g. https://github.com/EMODnet/EMODnetWFS/actions/runs/1499935741

@annakrystalli Can you have a look and merge if it is all ok? :raised_hands:

### CODE REVIEW

**Comment by salvafern** [comment]
Note this doesn't fix the R-CMD-Check. Seems like [currently the MacOS build is failling](https://github.com/EMODnet/EMODnetWFS/runs/4306310432?check_suite_focus=true#step:12:25). Partially because the terra package cannot be installed in MacOS (See https://github.com/rspatial/terra/issues/412)

**Comment by annakrystalli** [comment]
Nice one @salvafern ! I wonder if we want to remove the `on push` trigger and leave it on a scheduled cron job only?

**Comment by salvafern** [comment]
`on push` removed!

**Comment by annakrystalli** [comment]
As the UBUNTU checks seem to queue for ages and most passed last time, I'm going to go ahead and merge ok?

**Pull request merged**
